@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE4ODc2OTA2LCJpYXQiOjE3MTg4NzMzMDYsImp0aSI6IjEzMDY2YWZjMDEwMzQ3YTNhYThmMzY5MTBjMTg3MmJhIiwidXNlcl9pZCI6Mn0.Z-mHsBh9tfEwPoz11ni1smCDRc4AEZl-kIA14j6KcjM
###
# @name login
POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "g1@gmail.com",
    "password": "123456"
}
###
@jwt = {{login.response.body.access_token}}
###
GET http://localhost:8000/user/products
Authorization: Bearer {{jwt}}
Content-Type: application/json

###

GET http://localhost:8000/user/products/by-cate
Authorization: Bearer {{jwt}}
Content-Type: application/json

###

GET http://localhost:8000/user/products/by-id/1
Authorization: Bearer {{jwt}}
Content-Type: application/json
