# @name login
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "username": "g1@gmail.com",
    "password": "123456"
}
###
@jwt = {{login.response.body.access_token}}

###
GET http://localhost:8000/carts/getall
Authorization: Bearer {{jwt}}
Content-Type: application/json

###
POST http://localhost:8000/carts/add
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "product": 2, "quantity": 21
}

###
POST http://localhost:8000/carts/add
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "items" : [
        {"product": 4, "quantity": 10},
        {"product": 6, "quantity": 15}
    ]
}

###
PUT http://localhost:8000/carts/update
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    [
        {"id": 1, "product": 4, "cart_quantity": 5},
        {"id": 2, "product": 5, "cart_quantity": 10}
    ]
}
###
PUT http://localhost:8000/carts/update/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "product": 2, "cart_quantity": 2
}
###
DELETE http://localhost:8000/user/carts/1
Authorization: Bearer {{jwt}}
Content-Type: application/json


###
DELETE http://localhost:8000/user/carts/1
Authorization: Bearer {{jwt}}
Content-Type: application/json


###